---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oukygmkd/public_html
    # clean target
    - /bin/rm -rf ${DEPLOYPATH}/*

    # copy site files
    - /bin/cp -R api ${DEPLOYPATH}/
    - /bin/cp -R assets ${DEPLOYPATH}/
    - /bin/cp index.html ${DEPLOYPATH}/
    - /bin/cp styles.css ${DEPLOYPATH}/
    - /bin/cp script.js ${DEPLOYPATH}/
    - /bin/cp contact.js ${DEPLOYPATH}/

    # add/refresh a version query (?v=YYYYMMDDHHMMSS) in the deployed index.html
    - 'export VER=$(date +%Y%m%d%H%M%S)'
    - '/bin/sed -i -E "s|(href=\\"styles\\.css)(\\?[^\\"]*)?\\\"|\\1?v=${VER}\\"|g" ${DEPLOYPATH}/index.html'
    - '/bin/sed -i -E "s|(src=\\"script\\.js)(\\?[^\\"]*)?\\\"|\\1?v=${VER}\\"|g"  ${DEPLOYPATH}/index.html'
    - '/bin/sed -i -E "s|(src=\\"contact\\.js)(\\?[^\\"]*)?\\\"|\\1?v=${VER}\\"|g" ${DEPLOYPATH}/index.html'

    # cache headers: HTML revalidates; assets may cache long (safe with ?v=...)
    - '/bin/printf "%s\n" "<IfModule mod_headers.c>" "  <FilesMatch \"\\.(css|js|png|jpe?g|gif|svg|webp|woff2)$\">" "    Header set Cache-Control \"public, max-age=31536000, immutable\"" "  </FilesMatch>" "  <FilesMatch \"\\.html?$\">" "    Header set Cache-Control \"no-cache\"" "  </FilesMatch>" "</IfModule>" > ${DEPLOYPATH}/.htaccess'