---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oukygmkd/public_html
    - /bin/rm -rf ${DEPLOYPATH}/*
    - /bin/cp -R assets ${DEPLOYPATH}/
    - /bin/cp index.html ${DEPLOYPATH}/
    - /bin/cp styles.css ${DEPLOYPATH}/
    - /bin/cp script.js ${DEPLOYPATH}/
    - /bin/cp contact.js ${DEPLOYPATH}/