---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oukygmkd/public_html
    - export VERSION="$(/usr/local/cpanel/3rdparty/bin/git rev-parse --short HEAD)-$(date +%Y%m%d%H%M%S)"
      
      # curățare destinație (atenție: păstrează ce ai nevoie dinainte, ex. .well-known)
      - /bin/rm -rf ${DEPLOYPATH}/*
      
      # copiere fișiere
      - /bin/cp -R assets ${DEPLOYPATH}/
      - /bin/cp -R api ${DEPLOYPATH}/
      - /bin/cp index.html ${DEPLOYPATH}/
      - /bin/cp styles.css ${DEPLOYPATH}/
      - /bin/cp script.js ${DEPLOYPATH}/
      - /bin/cp contact.js ${DEPLOYPATH}/
      
      # înlocuire placeholder @@VERSION@@ în toate fișierele HTML copiate
      - /usr/bin/find ${DEPLOYPATH} -type f -name "*.html" -exec /bin/sed -i -e "s/@@VERSION@@/${VERSION}/g" {} \;