---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oukygmkd/public_html
    # clean target so no stale files remain
    - /bin/rm -rf ${DEPLOYPATH}/*

    # copy folders
    - /bin/cp -R api ${DEPLOYPATH}/
    - /bin/cp -R assets ${DEPLOYPATH}/

    # copy top-level files
    - /bin/cp index.html ${DEPLOYPATH}/
    - /bin/cp styles.css ${DEPLOYPATH}/
    - /bin/cp script.js ${DEPLOYPATH}/
    - /bin/cp contact.js ${DEPLOYPATH}/